services:
    sqlserver-db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver-db
        environment:
          SA_PASSWORD: "Testing123"
          ACCEPT_EULA: "Y"
        ports:
            - "1450:1433"
        volumes:
        - C:/DockerVolumes/data:/var/opt/mssql/data
        - C:/DockerVolumes/log:/var/opt/mssql/log
        - C:/DockerVolumes/secrets:/var/opt/mssql/secrets
      
    taskmanager-app:
        build:
          context: .
          dockerfile: TaskManagement/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
          - sqlserver-db
        ports:
          - "1540:80"
